import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "@/app/config/themeRegistry";
import ThinWrapperSnackBar from "@/app/components/thinWrapper/snackBar";
import Providers from "@/app/config/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <ThemeRegistry options={{ key: "mui" }}>
            {children}
            <ThinWrapperSnackBar />
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}
